### PR TITLE
Using Bootstrap: Nextweb.com Clone

### PR DESCRIPTION
**Pull request by KennyUTN**
I have done the following using HTML/CSS and Bootstrap

-Designed navbar main part and footer of the page.
-Added responsiveness for the page to be adaptive to any resolution.
-Cloned the layout with placeholder content.

### CODE REVIEW

**Review by layzrd — COMMENTED** [review]
### Status: Invalid  ↩️
Hi @KennyUTN , 👏 You did very well on this project. I appreciate your efforts to achieve this milestone 🦍. Kindly fix the following issues.

[REQUIRED]

In this project,
I understood what happened in your repository. 
The Pull Request should have a meaningful title and a brief description such as details about the project technologies and techniques used to build it, the authors, the tasks you accomplished, etc.). Please check the following link.
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Connect me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
Hello team :wave: 
You have done a good job in getting this project this far. :clap: 
However, there are still some changes to be made :writing_hand: 
- [ ] Github action is not enabled on your project. Please follow this [link](https://github.com/microverseinc/linters-config/tree/master/html-css) to enable GitHub action on this project
- [ ] Please make your readme more professional. Make sure all the links you put there are correct and that you have as much information about the project as possible. 
- [ ] Please update your pull request title and description. They should be descriptive and contain basic information about what you have done in this project.
#### body
- [ ] The body of your webpage does not take up the whole width of the screen just like it does on the original website. Please update your clone to take up the width of its screen.
- [ ] The nav does not look like the original and it is not responsive across the different screen sizes. 
- original(large screen)
Screenshot from 2020-11-30 21-43-42
- your clone(large screen)
Screenshot from 2020-11-30 21-45-15
- original(tablet screen)
Screenshot from 2020-11-30 21-48-52
- your clone(tablet screen) 
Screenshot from 2020-11-30 21-49-44
- original(small screen)
Screenshot from 2020-11-30 21-50-45
- your clone(small screen)
Screenshot from 2020-11-30 21-51-23
- [ ] So basically if I have to screenshot all the parts you will need to make improvements, I might end up screenshotting the whole page. Apart from practicing using bootstrap, another aim of this project is to clone the Newsweek homepage. What that means is that your clone should look exactly like that of the original. I.e they should behave the same way, respond to different screen size the same way, and should also use the same font so that they look the same. Your clone should basically look exactly like the original webpage that you cloned. 
So what you should do now is to go back to your clone and update all the part that needs updating, that means all part that does not look and behave like the original webpage.
In the end, your clone should look and behave exactly like the original webpage.

Please request another review when you are done.

slack(@ebeagusamuel)

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @KennyUTN**

 
---
### Requested 🔴 

- [ ] you haven't implemented any of the changes required by the previous TSE. please go back and do so.

- [ ] the only implemented change was with the readme file. please make sure to do all of the other stuff required by the previous tse.

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by mahmoud717** [comment]
> # Changes Required ♻️
> Hello team 👋
> You have done a good job in getting this project this far. 👏
> However, there are still some changes to be made ✍️
> 
> * [ ]  Github action is not enabled on your project. Please follow this [link](https://github.com/microverseinc/linters-config/tree/master/html-css) to enable GitHub action on this project
> * [ ]  Please make your readme more professional. Make sure all the links you put there are correct and that you have as much information about the project as possible.
> * [ ]  Please update your pull request title and description. They should be descriptive and contain basic information about what you have done in this project.
> 
> #### body
> * [ ]  The body of your webpage does not take up the whole width of the screen just like it does on the original website. Please update your clone to take up the width of its screen.
> * [ ]  The nav does not look like the original and it is not responsive across the different screen sizes.
> * original(large screen)
>   Screenshot from 2020-11-30 21-43-42
> * your clone(large screen)
>   Screenshot from 2020-11-30 21-45-15
> * original(tablet screen)
>   Screenshot from 2020-11-30 21-48-52
> * your clone(tablet screen)
>   Screenshot from 2020-11-30 21-49-44
> * original(small screen)
>   Screenshot from 2020-11-30 21-50-45
> * your clone(small screen)
>   Screenshot from 2020-11-30 21-51-23
> * [ ]  So basically if I have to screenshot all the parts you will need to make improvements, I might end up screenshotting the whole page. Apart from practicing using bootstrap, another aim of this project is to clone the Newsweek homepage. What that means is that your clone should look exactly like that of the original. I.e they should behave the same way, respond to different screen size the same way, and should also use the same font so that they look the same. Your clone should basically look exactly like the original webpage that you cloned.
>   So what you should do now is to go back to your clone and update all the part that needs updating, that means all part that does not look and behave like the original webpage.
>   In the end, your clone should look and behave exactly like the original webpage.
> 
> Please request another review when you are done.
> 
> slack(@ebeagusamuel)

### please do these changes

**Review by Temmarie — CHANGES_REQUESTED** [review]
### Changes Required! :recycle:
Hi @KennyUTN  ! 👋 👋 
### You have done well so far :clap: However, you did not finish all the previous review changes. Kindly work on them and submit them for another code review.

**Recommended**


- [ ] Your project looks great. However, your project cannot be approved until you write a descriptive PR Message. It's essential that your repository is professional, as this is one of the things that potential colleagues will look at when recruiting team members. Please refer to [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more information.


- [ ] Please work on all the changes required by the previous TSE.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @KennyUTN  :handshake: :handshake: :handshake: 
:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
## Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] Still no github actions enabled for this repo, please follow the instructions on [this link](https://github.com/microverseinc/linters-config/tree/master/html-css) to know how you enable github actions in your html/css project
- [ ] Please change the acknowledgement of your readme file, currently it contains a text which cannot be considered as a professional acknowledgment, typically in that section you should have put whoever you think helped you, inspired you, gave you ideas to make this project complete.
- [ ] Please work again on description whch is in your readme file, it still presents some typo errors which makes it unprofessional. For example instead of writing `https://www.newsweek.com/` you wrote `https://nextweek.com/` please fix that, you can use [this app (grammarly)]() to be able to spot grammatical and typing mistakes from your readme file
- [ ] Pull Request description still looking unprofessional, you should talk a bit about the work you have completed on this Pull Request, in summary. Currently the text which is there, doesn't reflect technically the typical work you have done on this Pull request.
- [ ] These requested changes are not implemented yet, please impment them before you submit for the other review: 

> # Changes Required 
> Hello team 
> You have done a good job in getting this project this far. 
> However, there are still some changes to be made 
> 
> * [ ]  Github action is not enabled on your project. Please follow this [link](https://github.com/microverseinc/linters-config/tree/master/html-css) to enable GitHub action on this project
> * [ ]  Please make your readme more professional. Make sure all the links you put there are correct and that you have as much information about the project as possible.
> * [ ]  Please update your pull request title and description. They should be descriptive and contain basic information about what you have done in this project.
> 
> #### body
> * [ ]  The body of your webpage does not take up the whole width of the screen just like it does on the original website. Please update your clone to take up the width of its screen.
> * [ ]  The nav does not look like the original and it is not responsive across the different screen sizes.
> * original(large screen)
>   Screenshot from 2020-11-30 21-43-42
> * your clone(large screen)
>   Screenshot from 2020-11-30 21-45-15
> * original(tablet screen)
>   Screenshot from 2020-11-30 21-48-52
> * your clone(tablet screen)
>   Screenshot from 2020-11-30 21-49-44
> * original(small screen)
>   Screenshot from 2020-11-30 21-50-45
> * your clone(small screen)
>   Screenshot from 2020-11-30 21-51-23
> * [ ]  So basically if I have to screenshot all the parts you will need to make improvements, I might end up screenshotting the whole page. Apart from practicing using bootstrap, another aim of this project is to clone the Newsweek homepage. What that means is that your clone should look exactly like that of the original. I.e they should behave the same way, respond to different screen size the same way, and should also use the same font so that they look the same. Your clone should basically look exactly like the original webpage that you cloned.
>   So what you should do now is to go back to your clone and update all the part that needs updating, that means all part that does not look and behave like the original webpage.
>   In the end, your clone should look and behave exactly like the original webpage.
> 
> Please request another review when you are done.
> 
> slack(@ebeagusamuel)

If anything seems to be unclear to you, comment on this Pull request and mention me as [@descholar-ceo](https://github.com/descholar-ceo/)

| [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

**Comment by KennyUTN** [comment]
@descholar-ceo  Hey what's up!. I fixed the problem, it was the live demo link that did not update with every one of my pushes, so it looked like I did not do anything 😢.

On another note, I cant seem to install Github actions on this repo. Every time I try to push it says...

image 

I tried pulling before as the sign says but it still does not work.

Thanks for your review!.

**Review by PhillipUg — APPROVED** [review]
# Status: Project Approved! 🥇 
Congratulations on implementing the project requirements and getting this project approved. :+1:

You can merge this branch into the main branch when you're ready and go on to your next project.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime**

**Pull request merged**
